### ISSUE TITLE
Allow expanding posts so that large posts can be viewed.

### ISSUE THREAD

**Issue by Angular-Angel** [Agora-Project/agora-meteor#11]
How exactly should this be implemented? I can think of three ways, not necessarily mutually exclusive. One is opening the post in a separate tab or navigating to a separate page of just it, the second is merely expanding it's box on the graph, though that might play funny with the rest of the graph, and the third is opening it in a hovering text box. Any preferences?

**Comment by saulrh** [comment]
No idea, honestly. All have their uses. I want to pull up a lightbox or get a pop-out for a large post as in fanfiction, but if I'm integrating multiple posts I probably want them all on one screen and a hover-box or drag-resize would be better.

**Comment by Angular-Angel** [comment]
Maybe just implement two or three, then? They're not mutually exclusive, so long as I can find controls to bind them too.

**Comment by Angular-Angel** [comment]
Smashmaster put together a system for viewing posts on their own pages. Not super convenient if you don't want to leave the graph, though.

**Comment by Angular-Angel** [comment]
May or may not add new method for this. Closed for now.
