### ISSUE TITLE
Automagic graph layout

### ISSUE THREAD

**Issue by saulrh** [Agora-Project/agora-meteor#2]
https://en.wikipedia.org/wiki/Graph_drawing

Graphs in this project will be extremely non-planar, but will also cluster heavily. In the example forum, for example, I expect a lot of posts to remain within distinct "clusters", with limited cross-linkings between clusters - a specific example would be a cluster corresponding to a fanfic, with discussion clustering around the core work and "Update edited in!" posts, but few to no edges to clusters for other fiction and even fewer to the current events or philosophy clusters.

You can probably get decent results with a simple forces-based layout, but the domain knowledge from above should make more interesting approaches very effective. I'd suggest a hybrid approach that uses unsupervised learning to find clusters, followed by doing a layered algorithm inside clusters and then forces-based layout between clusters.

UI would probably be a "format my current view" type thing. If you want to be really fancy, you could alternatively do a pure forces-based layout, but do it incrementally, a bit at a time, so the user can watch their posts sort themselves into a readable order.

There are almost certainly libraries available for doing this efficiently. You may even be able to find one that does it with something like asm.js to make it realtime.

**Comment by Angular-Angel** [comment]
Oh, thank you! I'm actually currently working on redoing the force graph into a more sensible layout.

**Comment by Angular-Angel** [comment]
Well, we have the first implementation of a new graph layout. It's pretty basic, but it's there. You can see it on the overview page. We're going to work on upgrading it a bunch, and then implement it on the normal forum view.

**Comment by Angular-Angel** [comment]
We implemented the new layout on the general forum page. Still needs a lot of work, but it's a good start.
