### ISSUE TITLE
Compose textbox loses focus on mouseup when trying to write post

### ISSUE THREAD

**Issue by saulrh** [Agora-Project/agora-meteor#3]
Chrome Version 54.0.2840.71 m
Windows 10 version 1607 build 14965.1001

Tested in blank profile, so it's not any of my extensions.

Tabbing into the compose box works.

**Comment by Angular-Angel** [comment]
I think that's cause it doesn't gain focus - focus stays on the reply button you just clicked. I'll work on changing that immediately.

**Comment by Angular-Angel** [comment]
Done.
