### ISSUE TITLE
Composed a reply, can't get it to show up

### ISSUE THREAD

**Issue by saulrh** [Agora-Project/agora-meteor#4]
"Show Connecting Posts (1)" shows that my post was created, but clicking on the button doesn't appear to show the reply I posted.

**Comment by Angular-Angel** [comment]
Hmm. You responded to the "What forums and subforums should there be?", right? I can't view that post either. What did you reply with? Did it not have a title? That might have caused a validation error on the server. I should change that so it doesn't get past the client.

**Comment by saulrh** [comment]
> That might have caused a validation error on the server. I should change that so it doesn't get past the client.

Warning: client-side validation never helps. It just creates a security vulnerability where I can bypass the client and directly feed malformed data to the server, which has no validation.

> I can't view that post either. What did you reply with? Did it not have a title? 

I actually can't remember what the content of the post was. Forgetting to set a title does seem likely, since I can't remember setting one of those.

**Comment by Angular-Angel** [comment]
Well, the server does have validation. That's why your post isn't showing up. Though it still went and created a link for it, so clearly i need to fix that, too. :/

**Comment by saulrh** [comment]
Interesting. So it created an edge with a dangling pointer on one end?

**Comment by Angular-Angel** [comment]
Yeah, I guess. Or maybe the post is in the database, but can't be loaded and displayed? I'll try and dig through the database and logs and all that tomorrow, see if I can find it. :/

**Comment by Angular-Angel** [comment]
Well, I haven't been able to find the errant post. I added a couple additional validation checks that should stop such errors in the future, though. Feel free to reopen this thread if anything else like this happens.
