### ISSUE TITLE
Displaying previews of posts could use some work.

### ISSUE THREAD

**Issue by Angular-Angel** [Agora-Project/agora-meteor#49]
In particular, the condition for displaying previews is rather clumsy, and the previews often overlap each other, especially on mobile devices.

**Comment by joyeusenoelle** [comment]
Currently addressing the overlap issue with the 'post-shuffle' branch.

**Comment by Angular-Angel** [comment]
Alright, previews no longer overlap and I think I have a reasonable heuristic for deciding when to check and show them. Issue closed.
