### ISSUE TITLE
Add slider to adjust visual distance between nodes

### ISSUE THREAD

**Issue by joyeusenoelle** [Agora-Project/agora-meteor#52]
It's been suggested that the graph have closer spacing so posts are positioned closer together when the graph is zoomed in. This could be a per-user preference, with a slider to adjust the visual distance between nodes to suit each user's feel of space and clutteredness.

**Comment by Angular-Angel** [comment]
Are we sure this is best done through a slider? It seems like something that it would be better for the program to do automatically. :/

**Comment by joyeusenoelle** [comment]
Possibly a miscommunication: the idea is to have a single slider in the options menu that governs the distance between nodes in the graph for a given user. The slider doesn't necessarily have to have a 1:1 correlation with the visual distance; it could be logarithmic or just have three points on it ("Compact"/"Cozy"/"Comfortable", to borrow Google's terms), or...

The user wouldn't be directly affecting the distance between posts; they would be setting a preference, and allowing the program to adhere to that preference, rather than coding a single distance between nodes and expecting users to adjust to it.

**Comment by Angular-Angel** [comment]
No, I get that, but my point still stands - distance between posts should generally be whatever makes it most convenient for people to read, and that seems like it should depend more on the nodes than on the person. So it would seem that the program should automatically space posts so that theres just enough space between them to notice the separation, so users can keep their scrolling to a minimum.

**Comment by joyeusenoelle** [comment]
Isn't "whatever makes it most convenient for people to read" necessarily going to depend on the person doing the reading?

**Comment by Angular-Angel** [comment]
I wouldn't think so. I'd expect it to be a lot like paragraphs - you have a set distance between paragraphs in a text document and you leave it at that. :/

**Comment by joyeusenoelle** [comment]
If you don't think it's necessary, I'll leave it alone. :)

**Comment by Angular-Angel** [comment]
We'll, I'm not entirely certain. Are we sure we're both talking about the
same thing? You meant the space between posts when way zoomed in on the
graph, right? Not something else? :/

**Comment by joyeusenoelle** [comment]
I think so. This came up in the Discord chat last week, I think? I'll have to do some digging to find it.
