### ISSUE TITLE
Figure out user experience for posts with lots of relatives

### ISSUE THREAD

**Issue by saulrh** [Agora-Project/agora-meteor#7]
If people start making "index" posts you could end up with most posts having large chunks of the entire graph as ancestors. When you open one, especially via a bookmark or similar function, do you open up all hundred or thousand ancestors?

Similar for posts with lots of children.

**Comment by Angular-Angel** [comment]
I'm going to implement a feature for looking at the list of connecting posts and picking them out one by one. And change it so that you only mass load like 10 at a time. Eventually there will also be sorting algorithms to help with all this.
